name: Release CI

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: make zip
      run: make zip
      
    - name: print 
      run: echo $GITHUB_REF

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: cbz.zip
        asset_name: cbz.zip
        tag: ${{ github.ref }}
        overwrite: true
        body: "calibre cbz output plugin"

